#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Collections.Droid.Resource", IsApplication=true)]

namespace Collections.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int TheListView = 2130968578;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem_Dog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem_Kitten = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_MainMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_DynamicView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_FixedView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Page_MainMenuView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Page_PolymorphicView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_SpecificPositions = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SplashScreen = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
