#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FragmentSample.UI.Droid.Resource", IsApplication=true)]

namespace FragmentSample.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::FragmentSample.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::FragmentSample.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::FragmentSample.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::FragmentSample.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::FragmentSample.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::FragmentSample.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::FragmentSample.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxBind = global::FragmentSample.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxDropDownItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxGroupItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxItemTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxLang = global::FragmentSample.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxSource = global::FragmentSample.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxTemplate = global::FragmentSample.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvvmCrossTagId = global::FragmentSample.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvxBindingTagUnique = global::FragmentSample.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.Fragment.Resource.String.library_name = global::FragmentSample.UI.Droid.Resource.String.library_name;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxBind = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxLang = global::FragmentSample.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl = global::FragmentSample.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl_MvxTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView_MvxSource = global::FragmentSample.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxItemTemplate = global::FragmentSample.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int DialogButton = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int LoadingText = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int actualtabcontent = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int detail_fragment = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int list_fragment = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int switchFragmentButton = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int testButton = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int the_notes = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int title_line = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int titles_fragment = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int titles_fragment_holder = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int when_line = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog_Names = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_FirstHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_List = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_SecondHeader = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_Titles = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem_SimpleItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_DetailView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_FormView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_HomeView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_TabView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Page_TitlesView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int tabs_1 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int tabs_2 = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int tabs_3 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int tabs_3_big = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
